//
//  GUI_IconView.hpp
//  GUI_TextView
//
//  Created by Panutat Tejasen on 12/1/2562 BE.
//  Copyright © 2562 Jimmy Software Co., Ltd. All rights reserved.
//

#ifndef GUI_IconView_hpp
#define GUI_IconView_hpp

#include <stdio.h>
#include "GUI_TextView.h"

class GUI_IconView : public GUI_TextView {
    uint16_t icon;
public:
    static GUI_IconView *create( GUI_View *parent, uint16_t unicode, const char *fontname, int fontsize, int x=0, int y=0, int width=0, int height=0,
                                std::function<bool(SDL_Event* ev)>userEventHandler = NULL );
    GUI_IconView(GUI_View *parent, uint16_t unicode, const char *fontname, int fontsize, int x=0, int y=0, int width=0, int height=0,
                 std::function<bool(SDL_Event* ev)>userEventHandler = NULL);
    virtual ~GUI_IconView();
    
    virtual void setIcon( uint16_t unicode );
    
    SDL_Texture* createTextureFormUnicode(Uint16 unicode, SDL_Rect* rect=NULL);
    
    virtual void updateContent();
};

/*
#define kIcon_address_book              0xf2b9u
#define kIcon_address_card              0xf2bbu
#define kIcon_angry                     0xf556u
#define kIcon_arrow_alt_circle_down     0xf358u
#define kIcon_arrow_alt_circle_left     0xf359u
#define kIcon_arrow_alt_circle_right    0xf35au
#define kIcon_arrow_alt_circle_up       0xf35bu
#define kIcon_bell                      0xf0f3u
#define kIcon_bell_slash                0xf1f6u
#define kIcon_bookmark                  0xf02eu
#define kIcon_building                  0xf1adu
#define kIcon_calendar                  0xf133u
#define kIcon_calendar_alt              0xf073u
#define kIcon_calendar_check            0xf274u
#define kIcon_calendar_minus            0xf272u
#define kIcon_calendar_plus             0xf271u
#define kIcon_calendar_times            0xf273u
#define kIcon_caret_square_down         0xf150u
#define kIcon_caret_square_left         0xf191u
#define kIcon_caret_square_right        0xf152u
#define kIcon_caret_square_up           0xf151u
#define kIcon_chart_bar                 0xf080u
#define kIcon_check_circle              0xf058u
#define kIcon_check_square              0xf14au
#define kIcon_circle                    0xf111u
#define kIcon_clipboard                 0xf328u
#define kIcon_clock                     0xf017u
#define kIcon_clone                     0xf24du
#define kIcon_closed_captioning         0xf20au
#define kIcon_comment                   0xf075u
#define kIcon_comment_alt               0xf27au
#define kIcon_comment_dots              0xf4adu
#define kIcon_comments                  0xf086u
#define kIcon_compass                   0xf14eu
#define kIcon_copy                      0xf0c5u
#define kIcon_copyright                 0xf1f9u
#define kIcon_credit_card               0xf09du
#define kIcon_dizzy                     0xf567u
#define kIcon_dot_circle                0xf192u
#define kIcon_edit                      0xf044u
#define kIcon_envelope                  0xf0e0u
#define kIcon_envelope_open             0xf2b6u
#define kIcon_eye                       0xf06eu
#define kIcon_eye_slash                 0xf070u
#define kIcon_file                      0xf15bu
#define kIcon_file_alt                  0xf15cu
#define kIcon_file_archive              0xf1c6u
#define kIcon_file_audio                0xf1c7u
#define kIcon_file_code                 0xf1c9u
#define kIcon_file_excel                0xf1c3u
#define kIcon_file_image                0xf1c5u
#define kIcon_file_pdf                  0xf1c1u
#define kIcon_file_powerpoint           0xf1c4u
#define kIcon_file_video                0xf1c8u
#define kIcon_file_word                 0xf1c2u
#define kIcon_flag                      0xf024u
#define kIcon_flushed                   0xf579u
#define kIcon_folder                    0xf07bu
#define kIcon_folder_open               0xf07cu
#define kIcon_font_awesome_logo_full    0xf4e6u
#define kIcon_frown                     0xf119u
#define kIcon_frown_open                0xf57au
#define kIcon_futbol                    0xf1e3u
#define kIcon_gem                       0xf3a5u
#define kIcon_grimace                   0xf57fu
#define kIcon_grin                      0xf580u
#define kIcon_grin_alt                  0xf581u
#define kIcon_grin_beam                 0xf582u
#define kIcon_grin_beam_sweat           0xf583u
#define kIcon_grin_hearts               0xf584u
#define kIcon_grin_squint               0xf585u
#define kIcon_grin_squint_tears         0xf586u
#define kIcon_grin_stars                0xf587u
#define kIcon_grin_tears                0xf588u
#define kIcon_grin_tongue               0xf589u
#define kIcon_grin_tongue_squint        0xf58au
#define kIcon_grin_tongue_wink          0xf58bu
#define kIcon_grin_wink                 0xf58cu
#define kIcon_hand_lizard               0xf258u
#define kIcon_hand_paper                0xf256u
#define kIcon_hand_peace                0xf25bu
#define kIcon_hand_point_down           0xf0a7u
#define kIcon_hand_point_left           0xf0a5u
#define kIcon_hand_point_right          0xf0a4u
#define kIcon_hand_point_up             0xf0a6u
#define kIcon_hand_pointer              0xf25au
#define kIcon_hand_rock                 0xf255u
#define kIcon_hand_scissors             0xf257u
#define kIcon_hand_spock                0xf259u
#define kIcon_handshake                 0xf2b5u
#define kIcon_hdd                       0xf0a0u
#define kIcon_heart                     0xf004u
#define kIcon_hospital                  0xf0f8u
#define kIcon_hourglass                 0xf254u
#define kIcon_id_badge                  0xf2c1u
#define kIcon_id_card                   0xf2c2u
#define kIcon_image                     0xf03eu
#define kIcon_images                    0xf302u
#define kIcon_keyboard                  0xf11cu
#define kIcon_kiss                      0xf596u
#define kIcon_kiss_beam                 0xf597u
#define kIcon_kiss_wink_heart           0xf598u
#define kIcon_laugh                     0xf599u
#define kIcon_laugh_beam                0xf59au
#define kIcon_laugh_squint              0xf59bu
#define kIcon_laugh_wink                0xf59cu
#define kIcon_lemon                     0xf094u
#define kIcon_life_ring                 0xf1cdu
#define kIcon_lightbulb                 0xf0ebu
#define kIcon_list_alt                  0xf022u
#define kIcon_map                       0xf279u
#define kIcon_meh                       0xf11au
#define kIcon_meh_blank                 0xf5a4u
#define kIcon_meh_rolling_eyes          0xf5a5u
#define kIcon_minus_square              0xf146u
#define kIcon_money_bill_alt            0xf3d1u
#define kIcon_moon                      0xf186u
#define kIcon_newspaper                 0xf1eau
#define kIcon_object_group              0xf247u
#define kIcon_object_ungroup            0xf248u
#define kIcon_paper_plane               0xf1d8u
#define kIcon_pause_circle              0xf28bu
#define kIcon_play_circle               0xf144u
#define kIcon_plus_square               0xf0feu
#define kIcon_question_circle           0xf059u
#define kIcon_registered                0xf25du
#define kIcon_sad_cry                   0xf5b3u
#define kIcon_sad_tear                  0xf5b4u
#define kIcon_save                      0xf0c7u
#define kIcon_share_square              0xf14du
#define kIcon_smile                     0xf118u
#define kIcon_smile_beam                0xf5b8u
#define kIcon_smile_wink                0xf4dau
#define kIcon_snowflake                 0xf2dcu
#define kIcon_square                    0xf0c8u
#define kIcon_star                      0xf005u
#define kIcon_star_half                 0xf089u
#define kIcon_sticky_note               0xf249u
#define kIcon_stop_circle               0xf28du
#define kIcon_sun                       0xf185u
#define kIcon_surprise                  0xf5c2u
#define kIcon_thumbs_down               0xf165u
#define kIcon_thumbs_up                 0xf164u
#define kIcon_times_circle              0xf057u
#define kIcon_tired                     0xf5c8u
#define kIcon_trash_alt                 0xf2edu
#define kIcon_user                      0xf007u
#define kIcon_user_circle               0xf2bdu
#define kIcon_window_close              0xf410u
#define kIcon_window_maximize           0xf2d0u
#define kIcon_window_minimize           0xf2d1u
#define kIcon_window_restore            0xf2d2u
*/
#define kIcon_solid_ad                                      0xf641u
#define kIcon_solid_address_book                            0xf2b9u
#define kIcon_solid_address_card                            0xf2bbu
#define kIcon_solid_adjust                                  0xf042u
#define kIcon_solid_air_freshener                           0xf5d0u
#define kIcon_solid_align_center                            0xf037u
#define kIcon_solid_align_justify                           0xf039u
#define kIcon_solid_align_left                              0xf036u
#define kIcon_solid_align_right                             0xf038u
#define kIcon_solid_allergies                               0xf461u
#define kIcon_solid_ambulance                               0xf0f9u
#define kIcon_solid_american_sign_language_interpreting     0xf2a3u
#define kIcon_solid_anchor                                  0xf13du
#define kIcon_solid_angle_double_down                       0xf103u
#define kIcon_solid_angle_double_left                       0xf100u
#define kIcon_solid_angle_double_right                      0xf101u
#define kIcon_solid_angle_double_up                         0xf102u
#define kIcon_solid_angle_down                              0xf107u
#define kIcon_solid_angle_left                              0xf104u
#define kIcon_solid_angle_right                             0xf105u
#define kIcon_solid_angle_up                                0xf106u
#define kIcon_solid_angry                                   0xf556u
#define kIcon_solid_ankh                                    0xf644u
#define kIcon_solid_apple_alt                               0xf5d1u
#define kIcon_solid_archive                                 0xf187u
#define kIcon_solid_archway                                 0xf557u
#define kIcon_solid_arrow_alt_circle_down                   0xf358u
#define kIcon_solid_arrow_alt_circle_left                   0xf359u
#define kIcon_solid_arrow_alt_circle_right                  0xf35au
#define kIcon_solid_arrow_alt_circle_up                     0xf35bu
#define kIcon_solid_arrow_circle_down                       0xf0abu
#define kIcon_solid_arrow_circle_left                       0xf0a8u
#define kIcon_solid_arrow_circle_right                      0xf0a9u
#define kIcon_solid_arrow_circle_up                         0xf0aau
#define kIcon_solid_arrow_down                              0xf063u
#define kIcon_solid_arrow_left                              0xf060u
#define kIcon_solid_arrow_right                             0xf061u
#define kIcon_solid_arrow_up                                0xf062u
#define kIcon_solid_arrows_alt                              0xf0b2u
#define kIcon_solid_arrows_alt_h                            0xf337u
#define kIcon_solid_arrows_alt_v                            0xf338u
#define kIcon_solid_assistive_listening_systems             0xf2a2u
#define kIcon_solid_asterisk                                0xf069u
#define kIcon_solid_at                                      0xf1fau
#define kIcon_solid_atlas                                   0xf558u
#define kIcon_solid_atom                                    0xf5d2u
#define kIcon_solid_audio_description                       0xf29eu
#define kIcon_solid_award                                   0xf559u
#define kIcon_solid_baby                                    0xf77cu
#define kIcon_solid_baby_carriage                           0xf77du
#define kIcon_solid_backspace                               0xf55au
#define kIcon_solid_backward                                0xf04au
#define kIcon_solid_balance_scale                           0xf24eu
#define kIcon_solid_ban                                     0xf05eu
#define kIcon_solid_band_aid                                0xf462u
#define kIcon_solid_barcode                                 0xf02au
#define kIcon_solid_bars                                    0xf0c9u
#define kIcon_solid_baseball_ball                           0xf433u
#define kIcon_solid_basketball_ball                         0xf434u
#define kIcon_solid_bath                                    0xf2cdu
#define kIcon_solid_battery_empty                           0xf244u
#define kIcon_solid_battery_full                            0xf240u
#define kIcon_solid_battery_half                            0xf242u
#define kIcon_solid_battery_quarter                         0xf243u
#define kIcon_solid_battery_three_quarters                  0xf241u
#define kIcon_solid_bed                                     0xf236u
#define kIcon_solid_beer                                    0xf0fcu
#define kIcon_solid_bell                                    0xf0f3u
#define kIcon_solid_bell_slash                              0xf1f6u
#define kIcon_solid_bezier_curve                            0xf55bu
#define kIcon_solid_bible                                   0xf647u
#define kIcon_solid_bicycle                                 0xf206u
#define kIcon_solid_binoculars                              0xf1e5u
#define kIcon_solid_biohazard                               0xf780u
#define kIcon_solid_birthday_cake                           0xf1fdu
#define kIcon_solid_blender                                 0xf517u
#define kIcon_solid_blender_phone                           0xf6b6u
#define kIcon_solid_blind                                   0xf29du
#define kIcon_solid_blog                                    0xf781u
#define kIcon_solid_bold                                    0xf032u
#define kIcon_solid_bolt                                    0xf0e7u
#define kIcon_solid_bomb                                    0xf1e2u
#define kIcon_solid_bone                                    0xf5d7u
#define kIcon_solid_bong                                    0xf55cu
#define kIcon_solid_book                                    0xf02du
#define kIcon_solid_book_dead                               0xf6b7u
#define kIcon_solid_book_open                               0xf518u
#define kIcon_solid_book_reader                             0xf5dau
#define kIcon_solid_bookmark                                0xf02eu
#define kIcon_solid_bowling_ball                            0xf436u
#define kIcon_solid_box                                     0xf466u
#define kIcon_solid_box_open                                0xf49eu
#define kIcon_solid_boxes                                   0xf468u
#define kIcon_solid_braille                                 0xf2a1u
#define kIcon_solid_brain                                   0xf5dcu
#define kIcon_solid_briefcase                               0xf0b1u
#define kIcon_solid_briefcase_medical                       0xf469u
#define kIcon_solid_broadcast_tower                         0xf519u
#define kIcon_solid_broom                                   0xf51au
#define kIcon_solid_brush                                   0xf55du
#define kIcon_solid_bug                                     0xf188u
#define kIcon_solid_building                                0xf1adu
#define kIcon_solid_bullhorn                                0xf0a1u
#define kIcon_solid_bullseye                                0xf140u
#define kIcon_solid_burn                                    0xf46au
#define kIcon_solid_bus                                     0xf207u
#define kIcon_solid_bus_alt                                 0xf55eu
#define kIcon_solid_business_time                           0xf64au
#define kIcon_solid_calculator                              0xf1ecu
#define kIcon_solid_calendar                                0xf133u
#define kIcon_solid_calendar_alt                            0xf073u
#define kIcon_solid_calendar_check                          0xf274u
#define kIcon_solid_calendar_day                            0xf783u
#define kIcon_solid_calendar_minus                          0xf272u
#define kIcon_solid_calendar_plus                           0xf271u
#define kIcon_solid_calendar_times                          0xf273u
#define kIcon_solid_calendar_week                           0xf784u
#define kIcon_solid_camera                                  0xf030u
#define kIcon_solid_camera_retro                            0xf083u
#define kIcon_solid_campground                              0xf6bbu
#define kIcon_solid_candy_cane                              0xf786u
#define kIcon_solid_cannabis                                0xf55fu
#define kIcon_solid_capsules                                0xf46bu
#define kIcon_solid_car                                     0xf1b9u
#define kIcon_solid_car_alt                                 0xf5deu
#define kIcon_solid_car_battery                             0xf5dfu
#define kIcon_solid_car_crash                               0xf5e1u
#define kIcon_solid_car_side                                0xf5e4u
#define kIcon_solid_caret_down                              0xf0d7u
#define kIcon_solid_caret_left                              0xf0d9u
#define kIcon_solid_caret_right                             0xf0dau
#define kIcon_solid_caret_square_down                       0xf150u
#define kIcon_solid_caret_square_left                       0xf191u
#define kIcon_solid_caret_square_right                      0xf152u
#define kIcon_solid_caret_square_up                         0xf151u
#define kIcon_solid_caret_up                                0xf0d8u
#define kIcon_solid_carrot                                  0xf787u
#define kIcon_solid_cart_arrow_down                         0xf218u
#define kIcon_solid_cart_plus                               0xf217u
#define kIcon_solid_cash_register                           0xf788u
#define kIcon_solid_cat                                     0xf6beu
#define kIcon_solid_certificate                             0xf0a3u
#define kIcon_solid_chair                                   0xf6c0u
#define kIcon_solid_chalkboard                              0xf51bu
#define kIcon_solid_chalkboard_teacher                      0xf51cu
#define kIcon_solid_charging_station                        0xf5e7u
#define kIcon_solid_chart_area                              0xf1feu
#define kIcon_solid_chart_bar                               0xf080u
#define kIcon_solid_chart_line                              0xf201u
#define kIcon_solid_chart_pie                               0xf200u
#define kIcon_solid_check                                   0xf00cu
#define kIcon_solid_check_circle                            0xf058u
#define kIcon_solid_check_double                            0xf560u
#define kIcon_solid_check_square                            0xf14au
#define kIcon_solid_chess                                   0xf439u
#define kIcon_solid_chess_bishop                            0xf43au
#define kIcon_solid_chess_board                             0xf43cu
#define kIcon_solid_chess_king                              0xf43fu
#define kIcon_solid_chess_knight                            0xf441u
#define kIcon_solid_chess_pawn                              0xf443u
#define kIcon_solid_chess_queen                             0xf445u
#define kIcon_solid_chess_rook                              0xf447u
#define kIcon_solid_chevron_circle_down                     0xf13au
#define kIcon_solid_chevron_circle_left                     0xf137u
#define kIcon_solid_chevron_circle_right                    0xf138u
#define kIcon_solid_chevron_circle_up                       0xf139u
#define kIcon_solid_chevron_down                            0xf078u
#define kIcon_solid_chevron_left                            0xf053u
#define kIcon_solid_chevron_right                           0xf054u
#define kIcon_solid_chevron_up                              0xf077u
#define kIcon_solid_child                                   0xf1aeu
#define kIcon_solid_church                                  0xf51du
#define kIcon_solid_circle                                  0xf111u
#define kIcon_solid_circle_notch                            0xf1ceu
#define kIcon_solid_city                                    0xf64fu
#define kIcon_solid_clipboard                               0xf328u
#define kIcon_solid_clipboard_check                         0xf46cu
#define kIcon_solid_clipboard_list                          0xf46du
#define kIcon_solid_clock                                   0xf017u
#define kIcon_solid_clone                                   0xf24du
#define kIcon_solid_closed_captioning                       0xf20au
#define kIcon_solid_cloud                                   0xf0c2u
#define kIcon_solid_cloud_download_alt                      0xf381u
#define kIcon_solid_cloud_meatball                          0xf73bu
#define kIcon_solid_cloud_moon                              0xf6c3u
#define kIcon_solid_cloud_moon_rain                         0xf73cu
#define kIcon_solid_cloud_rain                              0xf73du
#define kIcon_solid_cloud_showers_heavy                     0xf740u
#define kIcon_solid_cloud_sun                               0xf6c4u
#define kIcon_solid_cloud_sun_rain                          0xf743u
#define kIcon_solid_cloud_upload_alt                        0xf382u
#define kIcon_solid_cocktail                                0xf561u
#define kIcon_solid_code                                    0xf121u
#define kIcon_solid_code_branch                             0xf126u
#define kIcon_solid_coffee                                  0xf0f4u
#define kIcon_solid_cog                                     0xf013u
#define kIcon_solid_cogs                                    0xf085u
#define kIcon_solid_coins                                   0xf51eu
#define kIcon_solid_columns                                 0xf0dbu
#define kIcon_solid_comment                                 0xf075u
#define kIcon_solid_comment_alt                             0xf27au
#define kIcon_solid_comment_dollar                          0xf651u
#define kIcon_solid_comment_dots                            0xf4adu
#define kIcon_solid_comment_slash                           0xf4b3u
#define kIcon_solid_comments                                0xf086u
#define kIcon_solid_comments_dollar                         0xf653u
#define kIcon_solid_compact_disc                            0xf51fu
#define kIcon_solid_compass                                 0xf14eu
#define kIcon_solid_compress                                0xf066u
#define kIcon_solid_compress_arrows_alt                     0xf78cu
#define kIcon_solid_concierge_bell                          0xf562u
#define kIcon_solid_cookie                                  0xf563u
#define kIcon_solid_cookie_bite                             0xf564u
#define kIcon_solid_copy                                    0xf0c5u
#define kIcon_solid_copyright                               0xf1f9u
#define kIcon_solid_couch                                   0xf4b8u
#define kIcon_solid_credit_card                             0xf09du
#define kIcon_solid_crop                                    0xf125u
#define kIcon_solid_crop_alt                                0xf565u
#define kIcon_solid_cross                                   0xf654u
#define kIcon_solid_crosshairs                              0xf05bu
#define kIcon_solid_crow                                    0xf520u
#define kIcon_solid_crown                                   0xf521u
#define kIcon_solid_cube                                    0xf1b2u
#define kIcon_solid_cubes                                   0xf1b3u
#define kIcon_solid_cut                                     0xf0c4u
#define kIcon_solid_database                                0xf1c0u
#define kIcon_solid_deaf                                    0xf2a4u
#define kIcon_solid_democrat                                0xf747u
#define kIcon_solid_desktop                                 0xf108u
#define kIcon_solid_dharmachakra                            0xf655u
#define kIcon_solid_diagnoses                               0xf470u
#define kIcon_solid_dice                                    0xf522u
#define kIcon_solid_dice_d20                                0xf6cfu
#define kIcon_solid_dice_d6                                 0xf6d1u
#define kIcon_solid_dice_five                               0xf523u
#define kIcon_solid_dice_four                               0xf524u
#define kIcon_solid_dice_one                                0xf525u
#define kIcon_solid_dice_six                                0xf526u
#define kIcon_solid_dice_three                              0xf527u
#define kIcon_solid_dice_two                                0xf528u
#define kIcon_solid_digital_tachograph                      0xf566u
#define kIcon_solid_directions                              0xf5ebu
#define kIcon_solid_divide                                  0xf529u
#define kIcon_solid_dizzy                                   0xf567u
#define kIcon_solid_dna                                     0xf471u
#define kIcon_solid_dog                                     0xf6d3u
#define kIcon_solid_dollar_sign                             0xf155u
#define kIcon_solid_dolly                                   0xf472u
#define kIcon_solid_dolly_flatbed                           0xf474u
#define kIcon_solid_donate                                  0xf4b9u
#define kIcon_solid_door_closed                             0xf52au
#define kIcon_solid_door_open                               0xf52bu
#define kIcon_solid_dot_circle                              0xf192u
#define kIcon_solid_dove                                    0xf4bau
#define kIcon_solid_download                                0xf019u
#define kIcon_solid_drafting_compass                        0xf568u
#define kIcon_solid_dragon                                  0xf6d5u
#define kIcon_solid_draw_polygon                            0xf5eeu
#define kIcon_solid_drum                                    0xf569u
#define kIcon_solid_drum_steelpan                           0xf56au
#define kIcon_solid_drumstick_bite                          0xf6d7u
#define kIcon_solid_dumbbell                                0xf44bu
#define kIcon_solid_dumpster                                0xf793u
#define kIcon_solid_dumpster_fire                           0xf794u
#define kIcon_solid_dungeon                                 0xf6d9u
#define kIcon_solid_edit                                    0xf044u
#define kIcon_solid_eject                                   0xf052u
#define kIcon_solid_ellipsis_h                              0xf141u
#define kIcon_solid_ellipsis_v                              0xf142u
#define kIcon_solid_envelope                                0xf0e0u
#define kIcon_solid_envelope_open                           0xf2b6u
#define kIcon_solid_envelope_open_text                      0xf658u
#define kIcon_solid_envelope_square                         0xf199u
#define kIcon_solid_equals                                  0xf52cu
#define kIcon_solid_eraser                                  0xf12du
#define kIcon_solid_ethernet                                0xf796u
#define kIcon_solid_euro_sign                               0xf153u
#define kIcon_solid_exchange_alt                            0xf362u
#define kIcon_solid_exclamation                             0xf12au
#define kIcon_solid_exclamation_circle                      0xf06au
#define kIcon_solid_exclamation_triangle                    0xf071u
#define kIcon_solid_expand                                  0xf065u
#define kIcon_solid_expand_arrows_alt                       0xf31eu
#define kIcon_solid_external_link_alt                       0xf35du
#define kIcon_solid_external_link_square_alt                0xf360u
#define kIcon_solid_eye                                     0xf06eu
#define kIcon_solid_eye_dropper                             0xf1fbu
#define kIcon_solid_eye_slash                               0xf070u
#define kIcon_solid_fast_backward                           0xf049u
#define kIcon_solid_fast_forward                            0xf050u
#define kIcon_solid_fax                                     0xf1acu
#define kIcon_solid_feather                                 0xf52du
#define kIcon_solid_feather_alt                             0xf56bu
#define kIcon_solid_female                                  0xf182u
#define kIcon_solid_fighter_jet                             0xf0fbu
#define kIcon_solid_file                                    0xf15bu
#define kIcon_solid_file_alt                                0xf15cu
#define kIcon_solid_file_archive                            0xf1c6u
#define kIcon_solid_file_audio                              0xf1c7u
#define kIcon_solid_file_code                               0xf1c9u
#define kIcon_solid_file_contract                           0xf56cu
#define kIcon_solid_file_csv                                0xf6ddu
#define kIcon_solid_file_download                           0xf56du
#define kIcon_solid_file_excel                              0xf1c3u
#define kIcon_solid_file_export                             0xf56eu
#define kIcon_solid_file_image                              0xf1c5u
#define kIcon_solid_file_import                             0xf56fu
#define kIcon_solid_file_invoice                            0xf570u
#define kIcon_solid_file_invoice_dollar                     0xf571u
#define kIcon_solid_file_medical                            0xf477u
#define kIcon_solid_file_medical_alt                        0xf478u
#define kIcon_solid_file_pdf                                0xf1c1u
#define kIcon_solid_file_powerpoint                         0xf1c4u
#define kIcon_solid_file_prescription                       0xf572u
#define kIcon_solid_file_signature                          0xf573u
#define kIcon_solid_file_upload                             0xf574u
#define kIcon_solid_file_video                              0xf1c8u
#define kIcon_solid_file_word                               0xf1c2u
#define kIcon_solid_fill                                    0xf575u
#define kIcon_solid_fill_drip                               0xf576u
#define kIcon_solid_film                                    0xf008u
#define kIcon_solid_filter                                  0xf0b0u
#define kIcon_solid_fingerprint                             0xf577u
#define kIcon_solid_fire                                    0xf06du
#define kIcon_solid_fire_alt                                0xf7e4u
#define kIcon_solid_fire_extinguisher                       0xf134u
#define kIcon_solid_first_aid                               0xf479u
#define kIcon_solid_fish                                    0xf578u
#define kIcon_solid_fist_raised                             0xf6deu
#define kIcon_solid_flag                                    0xf024u
#define kIcon_solid_flag_checkered                          0xf11eu
#define kIcon_solid_flag_usa                                0xf74du
#define kIcon_solid_flask                                   0xf0c3u
#define kIcon_solid_flushed                                 0xf579u
#define kIcon_solid_folder                                  0xf07bu
#define kIcon_solid_folder_minus                            0xf65du
#define kIcon_solid_folder_open                             0xf07cu
#define kIcon_solid_folder_plus                             0xf65eu
#define kIcon_solid_font                                    0xf031u
#define kIcon_solid_font_awesome_logo_full                  0xf4e6u
#define kIcon_solid_football_ball                           0xf44eu
#define kIcon_solid_forward                                 0xf04eu
#define kIcon_solid_frog                                    0xf52eu
#define kIcon_solid_frown                                   0xf119u
#define kIcon_solid_frown_open                              0xf57au
#define kIcon_solid_funnel_dollar                           0xf662u
#define kIcon_solid_futbol                                  0xf1e3u
#define kIcon_solid_gamepad                                 0xf11bu
#define kIcon_solid_gas_pump                                0xf52fu
#define kIcon_solid_gavel                                   0xf0e3u
#define kIcon_solid_gem                                     0xf3a5u
#define kIcon_solid_genderless                              0xf22du
#define kIcon_solid_ghost                                   0xf6e2u
#define kIcon_solid_gift                                    0xf06bu
#define kIcon_solid_gifts                                   0xf79cu
#define kIcon_solid_glass_cheers                            0xf79fu
#define kIcon_solid_glass_martini                           0xf000u
#define kIcon_solid_glass_martini_alt                       0xf57bu
#define kIcon_solid_glass_whiskey                           0xf7a0u
#define kIcon_solid_glasses                                 0xf530u
#define kIcon_solid_globe                                   0xf0acu
#define kIcon_solid_globe_africa                            0xf57cu
#define kIcon_solid_globe_americas                          0xf57du
#define kIcon_solid_globe_asia                              0xf57eu
#define kIcon_solid_globe_europe                            0xf7a2u
#define kIcon_solid_golf_ball                               0xf450u
#define kIcon_solid_gopuram                                 0xf664u
#define kIcon_solid_graduation_cap                          0xf19du
#define kIcon_solid_greater_than                            0xf531u
#define kIcon_solid_greater_than_equal                      0xf532u
#define kIcon_solid_grimace                                 0xf57fu
#define kIcon_solid_grin                                    0xf580u
#define kIcon_solid_grin_alt                                0xf581u
#define kIcon_solid_grin_beam                               0xf582u
#define kIcon_solid_grin_beam_sweat                         0xf583u
#define kIcon_solid_grin_hearts                             0xf584u
#define kIcon_solid_grin_squint                             0xf585u
#define kIcon_solid_grin_squint_tears                       0xf586u
#define kIcon_solid_grin_stars                              0xf587u
#define kIcon_solid_grin_tears                              0xf588u
#define kIcon_solid_grin_tongue                             0xf589u
#define kIcon_solid_grin_tongue_squint                      0xf58au
#define kIcon_solid_grin_tongue_wink                        0xf58bu
#define kIcon_solid_grin_wink                               0xf58cu
#define kIcon_solid_grip_horizontal                         0xf58du
#define kIcon_solid_grip_lines                              0xf7a4u
#define kIcon_solid_grip_lines_vertical                     0xf7a5u
#define kIcon_solid_grip_vertical                           0xf58eu
#define kIcon_solid_guitar                                  0xf7a6u
#define kIcon_solid_h_square                                0xf0fdu
#define kIcon_solid_hammer                                  0xf6e3u
#define kIcon_solid_hamsa                                   0xf665u
#define kIcon_solid_hand_holding                            0xf4bdu
#define kIcon_solid_hand_holding_heart                      0xf4beu
#define kIcon_solid_hand_holding_usd                        0xf4c0u
#define kIcon_solid_hand_lizard                             0xf258u
#define kIcon_solid_hand_paper                              0xf256u
#define kIcon_solid_hand_peace                              0xf25bu
#define kIcon_solid_hand_point_down                         0xf0a7u
#define kIcon_solid_hand_point_left                         0xf0a5u
#define kIcon_solid_hand_point_right                        0xf0a4u
#define kIcon_solid_hand_point_up                           0xf0a6u
#define kIcon_solid_hand_pointer                            0xf25au
#define kIcon_solid_hand_rock                               0xf255u
#define kIcon_solid_hand_scissors                           0xf257u
#define kIcon_solid_hand_spock                              0xf259u
#define kIcon_solid_hands                                   0xf4c2u
#define kIcon_solid_hands_helping                           0xf4c4u
#define kIcon_solid_handshake                               0xf2b5u
#define kIcon_solid_hanukiah                                0xf6e6u
#define kIcon_solid_hashtag                                 0xf292u
#define kIcon_solid_hat_wizard                              0xf6e8u
#define kIcon_solid_haykal                                  0xf666u
#define kIcon_solid_hdd                                     0xf0a0u
#define kIcon_solid_heading                                 0xf1dcu
#define kIcon_solid_headphones                              0xf025u
#define kIcon_solid_headphones_alt                          0xf58fu
#define kIcon_solid_headset                                 0xf590u
#define kIcon_solid_heart                                   0xf004u
#define kIcon_solid_heart_broken                            0xf7a9u
#define kIcon_solid_heartbeat                               0xf21eu
#define kIcon_solid_helicopter                              0xf533u
#define kIcon_solid_highlighter                             0xf591u
#define kIcon_solid_hiking                                  0xf6ecu
#define kIcon_solid_hippo                                   0xf6edu
#define kIcon_solid_history                                 0xf1dau
#define kIcon_solid_hockey_puck                             0xf453u
#define kIcon_solid_holly_berry                             0xf7aau
#define kIcon_solid_home                                    0xf015u
#define kIcon_solid_horse                                   0xf6f0u
#define kIcon_solid_horse_head                              0xf7abu
#define kIcon_solid_hospital                                0xf0f8u
#define kIcon_solid_hospital_alt                            0xf47du
#define kIcon_solid_hospital_symbol                         0xf47eu
#define kIcon_solid_hot_tub                                 0xf593u
#define kIcon_solid_hotel                                   0xf594u
#define kIcon_solid_hourglass                               0xf254u
#define kIcon_solid_hourglass_end                           0xf253u
#define kIcon_solid_hourglass_half                          0xf252u
#define kIcon_solid_hourglass_start                         0xf251u
#define kIcon_solid_house_damage                            0xf6f1u
#define kIcon_solid_hryvnia                                 0xf6f2u
#define kIcon_solid_i_cursor                                0xf246u
#define kIcon_solid_icicles                                 0xf7adu
#define kIcon_solid_id_badge                                0xf2c1u
#define kIcon_solid_id_card                                 0xf2c2u
#define kIcon_solid_id_card_alt                             0xf47fu
#define kIcon_solid_igloo                                   0xf7aeu
#define kIcon_solid_image                                   0xf03eu
#define kIcon_solid_images                                  0xf302u
#define kIcon_solid_inbox                                   0xf01cu
#define kIcon_solid_indent                                  0xf03cu
#define kIcon_solid_industry                                0xf275u
#define kIcon_solid_infinity                                0xf534u
#define kIcon_solid_info                                    0xf129u
#define kIcon_solid_info_circle                             0xf05au
#define kIcon_solid_italic                                  0xf033u
#define kIcon_solid_jedi                                    0xf669u
#define kIcon_solid_joint                                   0xf595u
#define kIcon_solid_journal_whills                          0xf66au
#define kIcon_solid_kaaba                                   0xf66bu
#define kIcon_solid_key                                     0xf084u
#define kIcon_solid_keyboard                                0xf11cu
#define kIcon_solid_khanda                                  0xf66du
#define kIcon_solid_kiss                                    0xf596u
#define kIcon_solid_kiss_beam                               0xf597u
#define kIcon_solid_kiss_wink_heart                         0xf598u
#define kIcon_solid_kiwi_bird                               0xf535u
#define kIcon_solid_landmark                                0xf66fu
#define kIcon_solid_language                                0xf1abu
#define kIcon_solid_laptop                                  0xf109u
#define kIcon_solid_laptop_code                             0xf5fcu
#define kIcon_solid_laugh                                   0xf599u
#define kIcon_solid_laugh_beam                              0xf59au
#define kIcon_solid_laugh_squint                            0xf59bu
#define kIcon_solid_laugh_wink                              0xf59cu
#define kIcon_solid_layer_group                             0xf5fdu
#define kIcon_solid_leaf                                    0xf06cu
#define kIcon_solid_lemon                                   0xf094u
#define kIcon_solid_less_than                               0xf536u
#define kIcon_solid_less_than_equal                         0xf537u
#define kIcon_solid_level_down_alt                          0xf3beu
#define kIcon_solid_level_up_alt                            0xf3bfu
#define kIcon_solid_life_ring                               0xf1cdu
#define kIcon_solid_lightbulb                               0xf0ebu
#define kIcon_solid_link                                    0xf0c1u
#define kIcon_solid_lira_sign                               0xf195u
#define kIcon_solid_list                                    0xf03au
#define kIcon_solid_list_alt                                0xf022u
#define kIcon_solid_list_ol                                 0xf0cbu
#define kIcon_solid_list_ul                                 0xf0cau
#define kIcon_solid_location_arrow                          0xf124u
#define kIcon_solid_lock                                    0xf023u
#define kIcon_solid_lock_open                               0xf3c1u
#define kIcon_solid_long_arrow_alt_down                     0xf309u
#define kIcon_solid_long_arrow_alt_left                     0xf30au
#define kIcon_solid_long_arrow_alt_right                    0xf30bu
#define kIcon_solid_long_arrow_alt_up                       0xf30cu
#define kIcon_solid_low_vision                              0xf2a8u
#define kIcon_solid_luggage_cart                            0xf59du
#define kIcon_solid_magic                                   0xf0d0u
#define kIcon_solid_magnet                                  0xf076u
#define kIcon_solid_mail_bulk                               0xf674u
#define kIcon_solid_male                                    0xf183u
#define kIcon_solid_map                                     0xf279u
#define kIcon_solid_map_marked                              0xf59fu
#define kIcon_solid_map_marked_alt                          0xf5a0u
#define kIcon_solid_map_marker                              0xf041u
#define kIcon_solid_map_marker_alt                          0xf3c5u
#define kIcon_solid_map_pin                                 0xf276u
#define kIcon_solid_map_signs                               0xf277u
#define kIcon_solid_marker                                  0xf5a1u
#define kIcon_solid_mars                                    0xf222u
#define kIcon_solid_mars_double                             0xf227u
#define kIcon_solid_mars_stroke                             0xf229u
#define kIcon_solid_mars_stroke_h                           0xf22bu
#define kIcon_solid_mars_stroke_v                           0xf22au
#define kIcon_solid_mask                                    0xf6fau
#define kIcon_solid_medal                                   0xf5a2u
#define kIcon_solid_medkit                                  0xf0fau
#define kIcon_solid_meh                                     0xf11au
#define kIcon_solid_meh_blank                               0xf5a4u
#define kIcon_solid_meh_rolling_eyes                        0xf5a5u
#define kIcon_solid_memory                                  0xf538u
#define kIcon_solid_menorah                                 0xf676u
#define kIcon_solid_mercury                                 0xf223u
#define kIcon_solid_meteor                                  0xf753u
#define kIcon_solid_microchip                               0xf2dbu
#define kIcon_solid_microphone                              0xf130u
#define kIcon_solid_microphone_alt                          0xf3c9u
#define kIcon_solid_microphone_alt_slash                    0xf539u
#define kIcon_solid_microphone_slash                        0xf131u
#define kIcon_solid_microscope                              0xf610u
#define kIcon_solid_minus                                   0xf068u
#define kIcon_solid_minus_circle                            0xf056u
#define kIcon_solid_minus_square                            0xf146u
#define kIcon_solid_mitten                                  0xf7b5u
#define kIcon_solid_mobile                                  0xf10bu
#define kIcon_solid_mobile_alt                              0xf3cdu
#define kIcon_solid_money_bill                              0xf0d6u
#define kIcon_solid_money_bill_alt                          0xf3d1u
#define kIcon_solid_money_bill_wave                         0xf53au
#define kIcon_solid_money_bill_wave_alt                     0xf53bu
#define kIcon_solid_money_check                             0xf53cu
#define kIcon_solid_money_check_alt                         0xf53du
#define kIcon_solid_monument                                0xf5a6u
#define kIcon_solid_moon                                    0xf186u
#define kIcon_solid_mortar_pestle                           0xf5a7u
#define kIcon_solid_mosque                                  0xf678u
#define kIcon_solid_motorcycle                              0xf21cu
#define kIcon_solid_mountain                                0xf6fcu
#define kIcon_solid_mouse_pointer                           0xf245u
#define kIcon_solid_mug_hot                                 0xf7b6u
#define kIcon_solid_music                                   0xf001u
#define kIcon_solid_network_wired                           0xf6ffu
#define kIcon_solid_neuter                                  0xf22cu
#define kIcon_solid_newspaper                               0xf1eau
#define kIcon_solid_not_equal                               0xf53eu
#define kIcon_solid_notes_medical                           0xf481u
#define kIcon_solid_object_group                            0xf247u
#define kIcon_solid_object_ungroup                          0xf248u
#define kIcon_solid_oil_can                                 0xf613u
#define kIcon_solid_om                                      0xf679u
#define kIcon_solid_otter                                   0xf700u
#define kIcon_solid_outdent                                 0xf03bu
#define kIcon_solid_paint_brush                             0xf1fcu
#define kIcon_solid_paint_roller                            0xf5aau
#define kIcon_solid_palette                                 0xf53fu
#define kIcon_solid_pallet                                  0xf482u
#define kIcon_solid_paper_plane                             0xf1d8u
#define kIcon_solid_paperclip                               0xf0c6u
#define kIcon_solid_parachute_box                           0xf4cdu
#define kIcon_solid_paragraph                               0xf1ddu
#define kIcon_solid_parking                                 0xf540u
#define kIcon_solid_passport                                0xf5abu
#define kIcon_solid_pastafarianism                          0xf67bu
#define kIcon_solid_paste                                   0xf0eau
#define kIcon_solid_pause                                   0xf04cu
#define kIcon_solid_pause_circle                            0xf28bu
#define kIcon_solid_paw                                     0xf1b0u
#define kIcon_solid_peace                                   0xf67cu
#define kIcon_solid_pen                                     0xf304u
#define kIcon_solid_pen_alt                                 0xf305u
#define kIcon_solid_pen_fancy                               0xf5acu
#define kIcon_solid_pen_nib                                 0xf5adu
#define kIcon_solid_pen_square                              0xf14bu
#define kIcon_solid_pencil_alt                              0xf303u
#define kIcon_solid_pencil_ruler                            0xf5aeu
#define kIcon_solid_people_carry                            0xf4ceu
#define kIcon_solid_percent                                 0xf295u
#define kIcon_solid_percentage                              0xf541u
#define kIcon_solid_person_booth                            0xf756u
#define kIcon_solid_phone                                   0xf095u
#define kIcon_solid_phone_slash                             0xf3ddu
#define kIcon_solid_phone_square                            0xf098u
#define kIcon_solid_phone_volume                            0xf2a0u
#define kIcon_solid_piggy_bank                              0xf4d3u
#define kIcon_solid_pills                                   0xf484u
#define kIcon_solid_place_of_worship                        0xf67fu
#define kIcon_solid_plane                                   0xf072u
#define kIcon_solid_plane_arrival                           0xf5afu
#define kIcon_solid_plane_departure                         0xf5b0u
#define kIcon_solid_play                                    0xf04bu
#define kIcon_solid_play_circle                             0xf144u
#define kIcon_solid_plug                                    0xf1e6u
#define kIcon_solid_plus                                    0xf067u
#define kIcon_solid_plus_circle                             0xf055u
#define kIcon_solid_plus_square                             0xf0feu
#define kIcon_solid_podcast                                 0xf2ceu
#define kIcon_solid_poll                                    0xf681u
#define kIcon_solid_poll_h                                  0xf682u
#define kIcon_solid_poo                                     0xf2feu
#define kIcon_solid_poo_storm                               0xf75au
#define kIcon_solid_poop                                    0xf619u
#define kIcon_solid_portrait                                0xf3e0u
#define kIcon_solid_pound_sign                              0xf154u
#define kIcon_solid_power_off                               0xf011u
#define kIcon_solid_pray                                    0xf683u
#define kIcon_solid_praying_hands                           0xf684u
#define kIcon_solid_prescription                            0xf5b1u
#define kIcon_solid_prescription_bottle                     0xf485u
#define kIcon_solid_prescription_bottle_alt                 0xf486u
#define kIcon_solid_print                                   0xf02fu
#define kIcon_solid_procedures                              0xf487u
#define kIcon_solid_project_diagram                         0xf542u
#define kIcon_solid_puzzle_piece                            0xf12eu
#define kIcon_solid_qrcode                                  0xf029u
#define kIcon_solid_question                                0xf128u
#define kIcon_solid_question_circle                         0xf059u
#define kIcon_solid_quidditch                               0xf458u
#define kIcon_solid_quote_left                              0xf10du
#define kIcon_solid_quote_right                             0xf10eu
#define kIcon_solid_quran                                   0xf687u
#define kIcon_solid_radiation                               0xf7b9u
#define kIcon_solid_radiation_alt                           0xf7bau
#define kIcon_solid_rainbow                                 0xf75bu
#define kIcon_solid_random                                  0xf074u
#define kIcon_solid_receipt                                 0xf543u
#define kIcon_solid_recycle                                 0xf1b8u
#define kIcon_solid_redo                                    0xf01eu
#define kIcon_solid_redo_alt                                0xf2f9u
#define kIcon_solid_registered                              0xf25du
#define kIcon_solid_reply                                   0xf3e5u
#define kIcon_solid_reply_all                               0xf122u
#define kIcon_solid_republican                              0xf75eu
#define kIcon_solid_restroom                                0xf7bdu
#define kIcon_solid_retweet                                 0xf079u
#define kIcon_solid_ribbon                                  0xf4d6u
#define kIcon_solid_ring                                    0xf70bu
#define kIcon_solid_road                                    0xf018u
#define kIcon_solid_robot                                   0xf544u
#define kIcon_solid_rocket                                  0xf135u
#define kIcon_solid_route                                   0xf4d7u
#define kIcon_solid_rss                                     0xf09eu
#define kIcon_solid_rss_square                              0xf143u
#define kIcon_solid_ruble_sign                              0xf158u
#define kIcon_solid_ruler                                   0xf545u
#define kIcon_solid_ruler_combined                          0xf546u
#define kIcon_solid_ruler_horizontal                        0xf547u
#define kIcon_solid_ruler_vertical                          0xf548u
#define kIcon_solid_running                                 0xf70cu
#define kIcon_solid_rupee_sign                              0xf156u
#define kIcon_solid_sad_cry                                 0xf5b3u
#define kIcon_solid_sad_tear                                0xf5b4u
#define kIcon_solid_satellite                               0xf7bfu
#define kIcon_solid_satellite_dish                          0xf7c0u
#define kIcon_solid_save                                    0xf0c7u
#define kIcon_solid_school                                  0xf549u
#define kIcon_solid_screwdriver                             0xf54au
#define kIcon_solid_scroll                                  0xf70eu
#define kIcon_solid_sd_card                                 0xf7c2u
#define kIcon_solid_search                                  0xf002u
#define kIcon_solid_search_dollar                           0xf688u
#define kIcon_solid_search_location                         0xf689u
#define kIcon_solid_search_minus                            0xf010u
#define kIcon_solid_search_plus                             0xf00eu
#define kIcon_solid_seedling                                0xf4d8u
#define kIcon_solid_server                                  0xf233u
#define kIcon_solid_shapes                                  0xf61fu
#define kIcon_solid_share                                   0xf064u
#define kIcon_solid_share_alt                               0xf1e0u
#define kIcon_solid_share_alt_square                        0xf1e1u
#define kIcon_solid_share_square                            0xf14du
#define kIcon_solid_shekel_sign                             0xf20bu
#define kIcon_solid_shield_alt                              0xf3edu
#define kIcon_solid_ship                                    0xf21au
#define kIcon_solid_shipping_fast                           0xf48bu
#define kIcon_solid_shoe_prints                             0xf54bu
#define kIcon_solid_shopping_bag                            0xf290u
#define kIcon_solid_shopping_basket                         0xf291u
#define kIcon_solid_shopping_cart                           0xf07au
#define kIcon_solid_shower                                  0xf2ccu
#define kIcon_solid_shuttle_van                             0xf5b6u
#define kIcon_solid_sign                                    0xf4d9u
#define kIcon_solid_sign_in_alt                             0xf2f6u
#define kIcon_solid_sign_language                           0xf2a7u
#define kIcon_solid_sign_out_alt                            0xf2f5u
#define kIcon_solid_signal                                  0xf012u
#define kIcon_solid_signature                               0xf5b7u
#define kIcon_solid_sim_card                                0xf7c4u
#define kIcon_solid_sitemap                                 0xf0e8u
#define kIcon_solid_skating                                 0xf7c5u
#define kIcon_solid_skiing                                  0xf7c9u
#define kIcon_solid_skiing_nordic                           0xf7cau
#define kIcon_solid_skull                                   0xf54cu
#define kIcon_solid_skull_crossbones                        0xf714u
#define kIcon_solid_slash                                   0xf715u
#define kIcon_solid_sleigh                                  0xf7ccu
#define kIcon_solid_sliders_h                               0xf1deu
#define kIcon_solid_smile                                   0xf118u
#define kIcon_solid_smile_beam                              0xf5b8u
#define kIcon_solid_smile_wink                              0xf4dau
#define kIcon_solid_smog                                    0xf75fu
#define kIcon_solid_smoking                                 0xf48du
#define kIcon_solid_smoking_ban                             0xf54du
#define kIcon_solid_sms                                     0xf7cdu
#define kIcon_solid_snowboarding                            0xf7ceu
#define kIcon_solid_snowflake                               0xf2dcu
#define kIcon_solid_snowman                                 0xf7d0u
#define kIcon_solid_snowplow                                0xf7d2u
#define kIcon_solid_socks                                   0xf696u
#define kIcon_solid_solar_panel                             0xf5bau
#define kIcon_solid_sort                                    0xf0dcu
#define kIcon_solid_sort_alpha_down                         0xf15du
#define kIcon_solid_sort_alpha_up                           0xf15eu
#define kIcon_solid_sort_amount_down                        0xf160u
#define kIcon_solid_sort_amount_up                          0xf161u
#define kIcon_solid_sort_down                               0xf0ddu
#define kIcon_solid_sort_numeric_down                       0xf162u
#define kIcon_solid_sort_numeric_up                         0xf163u
#define kIcon_solid_sort_up                                 0xf0deu
#define kIcon_solid_spa                                     0xf5bbu
#define kIcon_solid_space_shuttle                           0xf197u
#define kIcon_solid_spider                                  0xf717u
#define kIcon_solid_spinner                                 0xf110u
#define kIcon_solid_splotch                                 0xf5bcu
#define kIcon_solid_spray_can                               0xf5bdu
#define kIcon_solid_square                                  0xf0c8u
#define kIcon_solid_square_full                             0xf45cu
#define kIcon_solid_square_root_alt                         0xf698u
#define kIcon_solid_stamp                                   0xf5bfu
#define kIcon_solid_star                                    0xf005u
#define kIcon_solid_star_and_crescent                       0xf699u
#define kIcon_solid_star_half                               0xf089u
#define kIcon_solid_star_half_alt                           0xf5c0u
#define kIcon_solid_star_of_david                           0xf69au
#define kIcon_solid_star_of_life                            0xf621u
#define kIcon_solid_step_backward                           0xf048u
#define kIcon_solid_step_forward                            0xf051u
#define kIcon_solid_stethoscope                             0xf0f1u
#define kIcon_solid_sticky_note                             0xf249u
#define kIcon_solid_stop                                    0xf04du
#define kIcon_solid_stop_circle                             0xf28du
#define kIcon_solid_stopwatch                               0xf2f2u
#define kIcon_solid_store                                   0xf54eu
#define kIcon_solid_store_alt                               0xf54fu
#define kIcon_solid_stream                                  0xf550u
#define kIcon_solid_street_view                             0xf21du
#define kIcon_solid_strikethrough                           0xf0ccu
#define kIcon_solid_stroopwafel                             0xf551u
#define kIcon_solid_subscript                               0xf12cu
#define kIcon_solid_subway                                  0xf239u
#define kIcon_solid_suitcase                                0xf0f2u
#define kIcon_solid_suitcase_rolling                        0xf5c1u
#define kIcon_solid_sun                                     0xf185u
#define kIcon_solid_superscript                             0xf12bu
#define kIcon_solid_surprise                                0xf5c2u
#define kIcon_solid_swatchbook                              0xf5c3u
#define kIcon_solid_swimmer                                 0xf5c4u
#define kIcon_solid_swimming_pool                           0xf5c5u
#define kIcon_solid_synagogue                               0xf69bu
#define kIcon_solid_sync                                    0xf021u
#define kIcon_solid_sync_alt                                0xf2f1u
#define kIcon_solid_syringe                                 0xf48eu
#define kIcon_solid_table                                   0xf0ceu
#define kIcon_solid_table_tennis                            0xf45du
#define kIcon_solid_tablet                                  0xf10au
#define kIcon_solid_tablet_alt                              0xf3fau
#define kIcon_solid_tablets                                 0xf490u
#define kIcon_solid_tachometer_alt                          0xf3fdu
#define kIcon_solid_tag                                     0xf02bu
#define kIcon_solid_tags                                    0xf02cu
#define kIcon_solid_tape                                    0xf4dbu
#define kIcon_solid_tasks                                   0xf0aeu
#define kIcon_solid_taxi                                    0xf1bau
#define kIcon_solid_teeth                                   0xf62eu
#define kIcon_solid_teeth_open                              0xf62fu
#define kIcon_solid_temperature_high                        0xf769u
#define kIcon_solid_temperature_low                         0xf76bu
#define kIcon_solid_tenge                                   0xf7d7u
#define kIcon_solid_terminal                                0xf120u
#define kIcon_solid_text_height                             0xf034u
#define kIcon_solid_text_width                              0xf035u
#define kIcon_solid_th                                      0xf00au
#define kIcon_solid_th_large                                0xf009u
#define kIcon_solid_th_list                                 0xf00bu
#define kIcon_solid_theater_masks                           0xf630u
#define kIcon_solid_thermometer                             0xf491u
#define kIcon_solid_thermometer_empty                       0xf2cbu
#define kIcon_solid_thermometer_full                        0xf2c7u
#define kIcon_solid_thermometer_half                        0xf2c9u
#define kIcon_solid_thermometer_quarter                     0xf2cau
#define kIcon_solid_thermometer_three_quarters              0xf2c8u
#define kIcon_solid_thumbs_down                             0xf165u
#define kIcon_solid_thumbs_up                               0xf164u
#define kIcon_solid_thumbtack                               0xf08du
#define kIcon_solid_ticket_alt                              0xf3ffu
#define kIcon_solid_times                                   0xf00du
#define kIcon_solid_times_circle                            0xf057u
#define kIcon_solid_tint                                    0xf043u
#define kIcon_solid_tint_slash                              0xf5c7u
#define kIcon_solid_tired                                   0xf5c8u
#define kIcon_solid_toggle_off                              0xf204u
#define kIcon_solid_toggle_on                               0xf205u
#define kIcon_solid_toilet                                  0xf7d8u
#define kIcon_solid_toilet_paper                            0xf71eu
#define kIcon_solid_toolbox                                 0xf552u
#define kIcon_solid_tools                                   0xf7d9u
#define kIcon_solid_tooth                                   0xf5c9u
#define kIcon_solid_torah                                   0xf6a0u
#define kIcon_solid_torii_gate                              0xf6a1u
#define kIcon_solid_tractor                                 0xf722u
#define kIcon_solid_trademark                               0xf25cu
#define kIcon_solid_traffic_light                           0xf637u
#define kIcon_solid_train                                   0xf238u
#define kIcon_solid_tram                                    0xf7dau
#define kIcon_solid_transgender                             0xf224u
#define kIcon_solid_transgender_alt                         0xf225u
#define kIcon_solid_trash                                   0xf1f8u
#define kIcon_solid_trash_alt                               0xf2edu
#define kIcon_solid_tree                                    0xf1bbu
#define kIcon_solid_trophy                                  0xf091u
#define kIcon_solid_truck                                   0xf0d1u
#define kIcon_solid_truck_loading                           0xf4deu
#define kIcon_solid_truck_monster                           0xf63bu
#define kIcon_solid_truck_moving                            0xf4dfu
#define kIcon_solid_truck_pickup                            0xf63cu
#define kIcon_solid_tshirt                                  0xf553u
#define kIcon_solid_tty                                     0xf1e4u
#define kIcon_solid_tv                                      0xf26cu
#define kIcon_solid_umbrella                                0xf0e9u
#define kIcon_solid_umbrella_beach                          0xf5cau
#define kIcon_solid_underline                               0xf0cdu
#define kIcon_solid_undo                                    0xf0e2u
#define kIcon_solid_undo_alt                                0xf2eau
#define kIcon_solid_universal_access                        0xf29au
#define kIcon_solid_university                              0xf19cu
#define kIcon_solid_unlink                                  0xf127u
#define kIcon_solid_unlock                                  0xf09cu
#define kIcon_solid_unlock_alt                              0xf13eu
#define kIcon_solid_upload                                  0xf093u
#define kIcon_solid_user                                    0xf007u
#define kIcon_solid_user_alt                                0xf406u
#define kIcon_solid_user_alt_slash                          0xf4fau
#define kIcon_solid_user_astronaut                          0xf4fbu
#define kIcon_solid_user_check                              0xf4fcu
#define kIcon_solid_user_circle                             0xf2bdu
#define kIcon_solid_user_clock                              0xf4fdu
#define kIcon_solid_user_cog                                0xf4feu
#define kIcon_solid_user_edit                               0xf4ffu
#define kIcon_solid_user_friends                            0xf500u
#define kIcon_solid_user_graduate                           0xf501u
#define kIcon_solid_user_injured                            0xf728u
#define kIcon_solid_user_lock                               0xf502u
#define kIcon_solid_user_md                                 0xf0f0u
#define kIcon_solid_user_minus                              0xf503u
#define kIcon_solid_user_ninja                              0xf504u
#define kIcon_solid_user_plus                               0xf234u
#define kIcon_solid_user_secret                             0xf21bu
#define kIcon_solid_user_shield                             0xf505u
#define kIcon_solid_user_slash                              0xf506u
#define kIcon_solid_user_tag                                0xf507u
#define kIcon_solid_user_tie                                0xf508u
#define kIcon_solid_user_times                              0xf235u
#define kIcon_solid_users                                   0xf0c0u
#define kIcon_solid_users_cog                               0xf509u
#define kIcon_solid_utensil_spoon                           0xf2e5u
#define kIcon_solid_utensils                                0xf2e7u
#define kIcon_solid_vector_square                           0xf5cbu
#define kIcon_solid_venus                                   0xf221u
#define kIcon_solid_venus_double                            0xf226u
#define kIcon_solid_venus_mars                              0xf228u
#define kIcon_solid_vial                                    0xf492u
#define kIcon_solid_vials                                   0xf493u
#define kIcon_solid_video                                   0xf03du
#define kIcon_solid_video_slash                             0xf4e2u
#define kIcon_solid_vihara                                  0xf6a7u
#define kIcon_solid_volleyball_ball                         0xf45fu
#define kIcon_solid_volume_down                             0xf027u
#define kIcon_solid_volume_mute                             0xf6a9u
#define kIcon_solid_volume_off                              0xf026u
#define kIcon_solid_volume_up                               0xf028u
#define kIcon_solid_vote_yea                                0xf772u
#define kIcon_solid_vr_cardboard                            0xf729u
#define kIcon_solid_walking                                 0xf554u
#define kIcon_solid_wallet                                  0xf555u
#define kIcon_solid_warehouse                               0xf494u
#define kIcon_solid_water                                   0xf773u
#define kIcon_solid_weight                                  0xf496u
#define kIcon_solid_weight_hanging                          0xf5cdu
#define kIcon_solid_wheelchair                              0xf193u
#define kIcon_solid_wifi                                    0xf1ebu
#define kIcon_solid_wind                                    0xf72eu
#define kIcon_solid_window_close                            0xf410u
#define kIcon_solid_window_maximize                         0xf2d0u
#define kIcon_solid_window_minimize                         0xf2d1u
#define kIcon_solid_window_restore                          0xf2d2u
#define kIcon_solid_wine_bottle                             0xf72fu
#define kIcon_solid_wine_glass                              0xf4e3u
#define kIcon_solid_wine_glass_alt                          0xf5ceu
#define kIcon_solid_won_sign                                0xf159u
#define kIcon_solid_wrench                                  0xf0adu
#define kIcon_solid_x_ray                                   0xf497u
#define kIcon_solid_yen_sign                                0xf157u
#define kIcon_solid_yin_yang                                0xf6adu

#endif /* GUI_IconView_hpp */
